[package]
name = "gothic-organizer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
fltk = "1.5.8"
fltk-theme = "0.7.9"
hashbrown = "0.15.3"
chrono = "0.4.41"

#####################
### OPTIMIZATION ####
#####################

# [profile.release]
# strip = "debuginfo"
# lto = "fat"
# opt-level = "s"
# debug-assertions = false
# debug = false
