[package]
name = "gothic-organizer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
iced_core = "0.13.1"
iced = { version = "0.13.1", features = ['image', 'advanced'] }
iced_aw = "0.12.2"
rfd = "0.15.3"
hashbrown = "0.15.3"
chrono = "0.4.41"
ahash = "0.8.12"


#####################
### OPTIMIZATION ####
#####################

# [profile.release]
# strip = "debuginfo"
# lto = "fat"
# opt-level = "s"
# debug-assertions = false
# debug = false
