[package]
name = "gothic-organizer-rs"
version = "0.9.0"
edition = "2024"
authors = ["Zira3l137"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
iced_core = "0.13.1"
iced = { version = "0.13.1", features = ['image', 'svg', 'advanced'] }
iced_aw = "0.12.2"
rfd = "0.15.3"
hashbrown = "0.15.3"
chrono = "0.4.41"
ahash = "0.8.12"
ignore = "0.4.23"
log = "0.4.27"
env_logger = "0.11.8"
clap = { version = "4.5.40", features = ["derive"] }
zip = "4.2.0"
scopeguard = "1.2.0"


#####################
### OPTIMIZATION ####
#####################

# [profile.release]
# strip = "debuginfo"
# lto = "fat"
# opt-level = "s"
# debug-assertions = false
# debug = false
